### PR TITLE
Examples are added and coding practice improved

### PR DESCRIPTION
**Pull request by chetkhatri**
What were proposed in this Pull Request ?
* Custom Mapping to read HBase table and Write HBase table are explained with sample example code and appropriate comments for more than 22 tuples limitation.
* Config file is added to point data points for HBase such as table name, column family etc.
* Coding standards are being improved.

Since multiple companies are using this awesome connector due to simplicity of this spark package.

### CODE REVIEW

**Comment by chetkhatri** [comment]
@nicolaferraro Please review and do needful.

**Comment by nicolaferraro** [comment]
Thank you very much @chetkhatri!

:+1:

**Comment by chetkhatri** [comment]
@nicolaferraro I am wondering that why my username @chetkhatri could not show in commit ! Did you used cherry pick ?

**Comment by nicolaferraro** [comment]
No, I just merged. The commit seems not to be done with your username..

**Comment by chetkhatri** [comment]
@nicolaferraro Yeah, something weird ! Requesting you to revert the commit. Apologize for my mistake. I will give new PR with my correct username.

**Pull request merged**
